export enum AuthActionTypes {
  REGISTER_REQUEST = '[Auth] REGISTER_REQUEST',
  REGISTER_SUCCESS = '[Auth] REGISTER_SUCCESS',
  REGISTER_ERROR = '[Auth] REGISTER_ERROR',

  LOGIN_REQUEST = '[Auth] LOGIN_REQUEST',
  LOGIN_SUCCESS = '[Auth] LOGIN_SUCCESS',
  LOGIN_ERROR = '[Auth] LOGIN_ERROR',
}
